### ISSUE TITLE
Voice_Recv-mk3

### ISSUE THREAD

**Issue by ghost** [Gorialis/discord.py#9]
## Summary

I had your fork from before your commit 9 days ago. My .venv had your fork of **discord.py | 1.6.0a2595+ga06ec1d | 1.7.2**. This fork worked with audio recieve. Currently with your new fork, i'm trying to recreate a new .venv with your new fork **discord.py-2.0.0a3045+gbfa1f374** but voice_recv crashes when the bot joins voice channel trying to record. 

I don't really know how to use github, but if you could share the prior fork of discord.py | 1.6.0a2595+ga06ec1d; I'd really appreciate it. 
<html>

<body>

discord.py | 1.6.0a2595+ga06ec1d | 1.7.2
-- | -- | --

</body>
</html> 
<html>
<body>
-- | -- | --

</body>
</html>

## Reproduction Steps

Just joined my bot to voice channel to record audio, and pycharm stopped compiling.

## Checklist

- [ ] I have searched the open issues for duplicates.
- [ ] I have shown the entire traceback, if possible.
- [ ] I have removed my token from display, if visible.
- [ ] I have provided the intents that my bot is using.

**Comment by scarletcafe** [comment]
Neither of these commit hashes actually exist on this repository (if they did, you would be able to compare between them). I'm assuming you've probably made some commit change on your own or pulled or something, so I'd advise just installing the branch directly to see if it fixes things:
```sh
pip install -U "discord.py[voice] @ git+https://github.com/Gorialis/discord.py@voice-recv-mk3"
```
This is the 2.0 alpha though, so breakage is kind of to expected. I fixed merge conflicts when redoing the rebase, but I haven't actually checked if something within 2.0 makes the branch not work temporarily.
If you want to revert to the old rebase for the time being, it's a06ec1def95b, so you can install it using:
```sh
pip install -U "discord.py[voice] @ git+https://github.com/Gorialis/discord.py@a06ec1def95b"
```

**Comment by ADeadCrow** [comment]
I know this is a very long reply time. I didn't want to bother. 

When doing:
        pip install -U "discord.py[voice] @ git+https://github.com/Gorialis/discord.py@a06ec1def95b" 
        I get "No matching distribution found for discord-py (unavailable)" i've tried to fork your repo and
        manually install it but no use. 
When i do:
         pip install -U "discord.py[voice] @ git+https://github.com/Gorialis/discord.py@voice-recv-mk3" 
         package does install but is with the issue i was talking about before. 

Any suggestions, i'm sorry if i'm continuing to bother.  I was considering manually copying all 9 files with prior edits and overwriting them but it seemed risky. Thank you for your time.
